name: flutterfire_gen_todo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutterfire_gen_annotation: ^0.2.0-dev.1
  flutterfire_gen_utils: ^0.2.0-dev.1
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_test:
    sdk: flutter
  flutterfire_gen: ^0.2.0-dev.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
